export const DomainErrorCodes = {
  // Validation & Request (400)
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_REQUEST: "INVALID_REQUEST",
  INVALID_ID: "INVALID_ID",

  // Authentication & Authorization (401, 403)
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  INVALID_PASSWORD: "INVALID_PASSWORD",

  // Resource Errors (404, 409)
  NOT_FOUND: "NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",

  // Business Logic (403, 422)
  USER_INACTIVE: "USER_INACTIVE",
  USER_NO_PASSWORD: "USER_NO_PASSWORD",
  ACCESS_DENIED: "ACCESS_DENIED",

  // Server Errors (500, 503)
  INTERNAL_ERROR: "INTERNAL_ERROR",
  CREATE_ERROR: "CREATE_ERROR",
  UPDATE_ERROR: "UPDATE_ERROR",
  DELETE_ERROR: "DELETE_ERROR",
  RETRIEVE_ERROR: "RETRIEVE_ERROR",
  DB_ERROR: "DB_ERROR",
  DB_MAPPING_ERROR: "DB_MAPPING_ERROR",
  DB_INTEGRITY_ERROR: "DB_INTEGRITY_ERROR",

  RATE_LIMIT: "RATE_LIMIT",
} as const;

export type DomainErrorCode = (typeof DomainErrorCodes)[keyof typeof DomainErrorCodes];
